---
- name: Create the hosts file for all machines
  template: src=hosts.j2 dest=/etc/hosts

- name: set selinux permissive
  selinux:
    state: permissive
    policy: targeted

- name: set selinux disable
  selinux:
    state: disabled

- name: Refresh repository cache
  shell: yum clean all && yum makecache

- name: Install the epel-release package
  yum: name=epel-release state=present

- name: Create the repository for mongodb
  copy: src=mongodb-org-3.4.repo dest=/etc/yum.repos.d/mongodb-org-3.4.repo

- name: Install the mongodb package
  yum: name={{ item }} state=present
  with_items:
   - python-pip
   - policycoreutils-python
   - mongodb-org-mongos-{{mongodb_version}}
   - mongodb-org-shell-{{mongodb_version}}
   - mongodb-org-server-{{mongodb_version}}


- name: Install the latest pymongo package
  pip: name={{item}} state=latest
  with_items:
   - pip
    
- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} state=directory setype=mongod_var_lib_t recurse=true

- name: create log directory for mongodb
  file: path=/var/log/mongo state=directory setype=mongod_log_t recurse=true

- name: create run directory for mongodb
  file: path=/var/run/mongo state=directory setype=mongod_var_run_t seuser=system_u recurse=true

- name: Configure system settings, file descriptors and number of threads
  pam_limits:
    domain: '*'
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: 500000 }
    - { limit_type: '-', limit_item: 'nproc', value: 500000 }
    - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
    - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

- name: reload settings from all system configuration files
  shell: sysctl --system